[package]
name = "computational_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
csv = "1.3.0"
ndarray-csv = "0.5.2"
num = "0.4.1"